-- Create CMS Articles Table
CREATE TABLE IF NOT EXISTS cms_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE,              -- For URL friendly access (e.g., 'privacy-policy')
    cover_image TEXT,                      -- URL for the cover image
    summary VARCHAR(500),                  -- Short description for lists
    content TEXT,                          -- HTML or Rich Text content
    
    -- Taxonomy
    type VARCHAR(50) NOT NULL,             -- 'article', 'policy', 'faq', 'announcement'
    category VARCHAR(50),                  -- 'guide', 'news', 'health', 'real_estate'
    target_audience VARCHAR(20) DEFAULT 'all', -- 'all', 'user', 'provider'
    
    -- Status & Metrics
    status VARCHAR(20) DEFAULT 'published', -- 'draft', 'published', 'archived'
    views INT DEFAULT 0,
    sort_order INT DEFAULT 0,              -- Higher number = higher priority (useful for policies/FAQs)
    author_name VARCHAR(100) DEFAULT '有福家',
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_cms_type ON cms_articles(type);
CREATE INDEX IF NOT EXISTS idx_cms_slug ON cms_articles(slug);
CREATE INDEX IF NOT EXISTS idx_cms_status ON cms_articles(status);

-- Seed Data: 1. Frontend Articles (Based on user screenshot)
INSERT INTO cms_articles (title, type, category, cover_image, summary, views, content, created_at)
VALUES 
(
    '如何选择靠谱的维修师傅？', 
    'article', 
    'guide', 
    'https://images.unsplash.com/photo-1581578731117-104f8a338e2d?auto=format&fit=crop&w=800&q=80',
    '拒绝踩坑！这3点关键资质一定要看，教你轻松辨别专业服务商。',
    23000,
    '<p>我们在寻找家庭维修服务时，最怕遇到“游击队”或者乱收费的情况。本文将从资质审核、价格透明度和售后保障三个维度，手把手教你如何筛选出靠谱的维修师傅。</p><h3>1. 查看平台认证标识</h3><p>正规平台会对入驻师傅进行实名认证和技能考核...</p>',
    NOW() - INTERVAL '2 days'
),
(
    '家电清洗频率大揭秘', 
    'article', 
    'health', 
    'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
    '洗衣机不洗比马桶还脏？专家建议这些家电必须定期深度清洁。',
    15000,
    '<p>很多家庭只注重家电的表面清洁，却忽视了内部的卫生。洗衣机槽、空调滤网、油烟机内部往往是细菌的温床...</p>',
    NOW() - INTERVAL '5 days'
),
(
    '服务验收标准清单', 
    'article', 
    'guide', 
    'https://images.unsplash.com/photo-1505798577917-a651a5d40320?auto=format&fit=crop&w=800&q=80',
    '水管修完怎么验？电路安全怎么查？一份清单教你做验收专家。',
    9800,
    '<p>维修服务完成后，不要着急付款，先对照这份清单检查一遍。1. 查看是否有漏水痕迹...</p>',
    NOW() - INTERVAL '1 week'
),
(
    '二手房交易流程全解析', 
    'article', 
    'real_estate', 
    'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80',
    '从看房到过户，全流程节点梳理，让你买房卖房不迷路。',
    32000,
    '<p>二手房交易涉及环节众多，资金量大，风险也相对较高。我们梳理了标准的交易流程图...</p>',
    NOW() - INTERVAL '10 days'
);

-- Seed Data: 2. Policies (Protocols)
INSERT INTO cms_articles (title, slug, type, content)
VALUES 
(
    '用户注册协议', 
    'user-agreement', 
    'policy', 
    '<h1>用户注册协议</h1><p>欢迎您注册并使用有福家服务...</p>'
),
(
    '隐私政策', 
    'privacy-policy', 
    'policy', 
    '<h1>隐私政策</h1><p>我们需要收集您的以下信息以提供服务...</p>'
),
(
    '服务商入驻协议', 
    'provider-agreement', 
    'policy', 
    '<h1>服务商入驻协议</h1><p>作为服务商，您需要遵守以下行为规范...</p>'
);

-- Seed Data: 3. System Announcements
INSERT INTO cms_articles (title, type, summary, content, sort_order)
VALUES 
(
    '【重要】关于春节期间服务费调整的通知',
    'announcement',
    '春节期间部分服务价格将有小幅上调，请知悉。',
    '<p>尊敬的用户：春节期间由于人工成本上涨，我们将调整...</p>',
    10
);
